Add endpoint to return a provider based on the team_id
codelittinc/notifications pull request #74
Opened 2023-01-24 18:51 UTC by alessandromontividiu03

2023-01-25 16:16 UTC, kaiomagalhaes requested changes

2023-01-25 16:16 UTC, kaiomagalhaes commented on app/controllers/api/provider_credentials_controller.rb
> +    before_action :authenticate
as crazy as it sounds, I don't think we can authenticate here because our goal with getting the id is to get the key in roadrunner

2023-01-25 16:51 UTC, alessandromontividiu03 commented on app/controllers/api/provider_credentials_controller.rb
> +    before_action :authenticate
@kaiomagalhaes done, I just removed the authentication from this new endpoint

2023-01-26 15:33 UTC, kaiomagalhaes requested changes

2023-01-26 17:45 UTC, kaiomagalhaes approved these changes

2023-01-26 17:45 UTC, merged